### ISSUE TITLE
How could I run a demo wild video to see the visualization result

### ISSUE THREAD

**Issue by hujb48** [jfzhang95/PoseAug#10]
It‘s a great work!
And can you upload the The corresponding pre-trained model to evaluate any wild video and to see the visualization result if possible!
Best wishes!

**Comment by Garfield-kh** [comment]
Thanks for your interest!
Here are the steps to predict 3D pose (16 joints) from image/video:

1. Apply [OpenPose ](https://github.com/CMU-Perceptual-Computing-Lab/openpose) or [AlphaPose ](https://github.com/MVIG-SJTU/AlphaPose) to get the detect 2D. 
2. Then convert the detect 2D to 16 joints definition with a similar procedure as  [prepare_data_3dhp.py](https://github.com/jfzhang95/PoseAug/blob/main/data_extra/prepare_data_3dhp.py) .
3. Apply [Savgol filter](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.savgol_filter.html) to smooth the 2D pose.
4. Preprocess the 2D pose with the same normalization as the 2D-3D pose model training.
5. Apply the 2D-3D pose model on 2D pose to get the 3D pose result.
6. Visualization the 3D pose result with code [visualization.py](https://github.com/facebookresearch/VideoPose3D/blob/1afb1ca0f1237776518469876342fc8669d3f6a9/common/visualization.py#L62) 

We are busy with other stuffs currently, we will update you once we have time to clean the code.
Hope this helps.
Thank you.

**Comment by hujb48** [comment]
@Garfield-kh Thanks a lot for your prompt reply, I am a new at this field, I would try it by following this guide, maybe it would have some problems with test and hope to communicate with your team at your convenience!
Yours sincerely, Hu.

**Comment by Garfield-kh** [comment]
You are welcome~  :)

**Comment by hujb48** [comment]
Hi, there is another suggest that if you can give the pre-trained model trained with the trajectory model like [https://github.com/facebookresearch/VideoPose3D](url), the model would be better for visualization intuitively.
And Thanks again!

**Comment by Garfield-kh** [comment]
Thank you for the suggestion, will update you once we make it. ^-^

**Comment by hujb48** [comment]
:)

**Comment by JinShiyin** [comment]
Hi, the output  is relative to the 0 joint, how can I get the 0 joint's 3d location?

**Comment by Garfield-kh** [comment]
Hi, you may check this [3DMPPE_ROOTNET_RELEASE](https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE) or [VideoPose3D ](https://github.com/jfzhang95/PoseAug/issues/url) root location prediction.

**Comment by JinShiyin** [comment]
Ok, thank you for your reply.
