### ISSUE TITLE
pretrain the baseline model

### ISSUE THREAD

**Issue by JihuaPeng** [jfzhang95/PoseAug#11]
Your work is great! Thanks. when I run the command python3 run_baseline.py --note pretrain --lr 1e-3 --posenet_name 'videopose' --checkpoint './checkpoint/pretrain_baseline' --keypoints gt, the following error was generated
<img width="979" alt="image" src="https://user-images.githubusercontent.com/30943144/127501950-a2852c59-105b-44e8-8294-86035fc56251.png">
Can i trouble you to check what is wrong? Thanks!

**Comment by Garfield-kh** [comment]
Thanks for your interest.
This is due to the different joints setting, while ours is 16 joints, and the one you are using is 17 joints.
Please check this issue [issue #6](https://github.com/jfzhang95/PoseAug/issues/6).
Hope this helps.

**Comment by JihuaPeng** [comment]
Thanks for your reply.
However, when I train the baseline model with PoseAug by running the command python3 run_poseaug.py --note poseaug --posenet_name 'videopose' --lr_p 1e-4 --checkpoint './checkpoint/poseaug' --keypoints gt, the following error was generated
![image](https://user-images.githubusercontent.com/30943144/127758461-d1fd554a-1fe2-4a2e-9909-534b837e9267.png)
Can you help me see what went wrong? Thanks!

**Comment by Garfield-kh** [comment]
I am not sure here, can you try this [link](https://stackoverflow.com/questions/18649512/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe2-in-position-13-ordinal)?

**Comment by JihuaPeng** [comment]
Thanks for your reply！I have solved this problem.
