### ISSUE TITLE
the data preprocess pipeline

### ISSUE THREAD

**Issue by gravitychen** [jfzhang95/PoseAug#12]
Nice work! I draw the data preprocess pipeline here, can you help me to check its correctness

huamn3.6(17 world 3D joints) --> delete nose joint --> huamn3.6(16 world 3D joints) -->normalize 3D (/ 1000) -->huamn3.6( noramlized 16 world 3D joints)  --> normalize camera parameter and perspective projection --> get normalized 2D pose

MPI: delete nose --> (16 2D pose) --> normalize 2D using camera resolution -->input to poseaug -->predicted MPI 3D <==MPJPE protocal 1, PCK, AUC=>  GT MPI 3D, then the MPJPE protocal 1, PCK, AUC are recorded in your paper, Table2

Is this right? thank you very much~

**Comment by Garfield-kh** [comment]
Thanks for your interest.
Here the MPI 2D/3D pose are 24 joints setting, we convert it to 16 joints setting by [prepare_data_3dhp.py](https://github.com/jfzhang95/PoseAug/blob/main/data_extra/prepare_data_3dhp.py), with reason issue #4 
The others are right. :)

**Comment by gravitychen** [comment]
OK, Thank you very much!,I got it
