### ISSUE TITLE
How to do poseaug with larger receptive fields, i.e. more frames of VPOSE3D

### ISSUE THREAD

**Issue by mariolew** [jfzhang95/PoseAug#13]
And why this is not mentioned in the paper? Thanks.

**Comment by Garfield-kh** [comment]
Hi, thanks for your interest.
This work is main on single frame setting.
For multi-frames setting, we will update it soon.
Thank you~

**Comment by mariolew** [comment]
For multi-frame setting, the sequence of motion should use the same augmentation, am i right?
