### ISSUE TITLE
Question about feedback loss in code

### ISSUE THREAD

**Issue by MooreManor** [jfzhang95/PoseAug#15]
Hello. Thanks for your excellent job. 
I have some confusion about your feedback loss.
In your code, I think function(fix_hard_ratio_loss) in model_gan_train.py equals the feedback loss of equation (9) in the paper. But fix_hard_ratio_loss has never been called. You use fix_hardratio which is not mentioned in the paper to calculate the feedback loss. 
I want to know the meaning of fix_hardratio and why you don't use the fix_hard_ratio_loss?

**Comment by Garfield-kh** [comment]
Hello, thank you for the interest!
We updated feedback loss after submission. The fix_hardratio is the updated version. 
fix_hard_ratio_loss which encourages the hardness to be a single value,  while
fix_hardratio is a rectified L2 loss, which can adjust the hardness within a proper range.
This modification can help achieve better performance on 3DHP (VPose-GT: 71) and H36M (STGCN-GT: 36).

**Comment by MooreManor** [comment]
Thank you for the detailed answer!
