### ISSUE TITLE
how can i download data_extra/test_set/test_3dhp.npz

### ISSUE THREAD

**Issue by SungwookLE** [jfzhang95/PoseAug#16]
Hi,

`FileNotFoundError: [Errno 2] No such file or directory: 'data_extra/test_set/test_3dhp.npz`

how can i resolve it?
thanks.

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest.
Please refer to [DATASETS.md](https://github.com/jfzhang95/PoseAug/blob/main/DATASETS.md) for the preparation of the dataset files.
