### ISSUE TITLE
Pre-trained models (with PoseAug)

### ISSUE THREAD

**Issue by jacksoncsy** [jfzhang95/PoseAug#19]
Hello,

Thanks for open-sourcing your work, it is indeed a very nice project!
May I have your pre-trained models (with PoseAug) for comparison purposes? I can see that only pretrained ST-GCN (w. PoseAug) is available. 
It would be fantastic to have also pretrained SemGCN, SimpleBL and VPose3d. 

Many thanks,
Shiyang

**Comment by Garfield-kh** [comment]
Hi, Shiyang,
Thank you for the interest!
I have uploaded them in [here](https://drive.google.com/drive/folders/1mLttbyZxsRdN5kw1IRdzZozyfndhV3Wh?usp=sharing). 

Thank you~

**Comment by jacksoncsy** [comment]
Hello Kehong,

Fantastic! I really appreciate your efforts! 

Many thanks,
Shiyang
