### ISSUE TITLE
Question about the operation parameters

### ISSUE THREAD

**Issue by CheungBH** [jfzhang95/PoseAug#2]
Hello. Thanks for your excellent job. 
I have read your paper and I have some confusion about the details.
You mentioned that you have three operation parameters [γba, γbl and (R, t)] which represent the joint angles, bone length, and camera location respectively. They are generated by the augmentor.
I wonder that whether the [γba, γbl] are both floating number or a vector? It seems unlikely to be vectors in mathematic expression since they're writen in lower case, but if they are floating numbers, are all the bone length and bone angles will be changed with the same value?

**Comment by jfzhang95** [comment]
Hi, thanks for your interest in our work.

\gamma_{ba} and \gamma_{bl} are vectors. Different bones have different values.

**Comment by NoLookDefense** [comment]
> Hi, thanks for your interest in our work.
> 
> \gamma_{ba} and \gamma_{bl} are vectors. Different bones have different values.

Thank you. I wonder when the code will be released?
