### ISSUE TITLE
Regarding the 2D input

### ISSUE THREAD

**Issue by jacksoncsy** [jfzhang95/PoseAug#20]
Hello,

Sorry to bother you again, may I know which joint is not needed for your 2D input? Is it head, or nose? 
I understand that your input and output are both 16 joints, and nose is not predicted by the model.

Many thanks,
Shiyang

**Comment by Garfield-kh** [comment]
Hi, Shiyang,

Welcome~
Both 2D pose and 3D pose follow the same joint setting so that the virtual camera projection (3D pose 16x3 -> 2D pose 16x2) can be used as augmentation data directly.

**Comment by jacksoncsy** [comment]
Hey Kehong,

So the nose is excluded in both setting then? Thanks so much! 

Cheers,
Shiyang

**Comment by Garfield-kh** [comment]
Hi Shiyang,

Yes. :)
