### ISSUE TITLE
How should I save keypoints in npy format?

### ISSUE THREAD

**Issue by LMR2018** [jfzhang95/PoseAug#21]
How should I save keypoints in npy format?

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest.
Do you mean `np.save()?`

**Comment by LMR2018** [comment]
Where to print keypoints and how to export MP4 video files to 3D NPY format to save keypoints
I want to convert the video like this and save it as Npy:

The file should contain an array with shape 15 x 2 x length.
The first dimension (15) corresponds the 15 body joint defined here.
The second dimension (2) corresponds to x and y coordinates.
The third dimension (length) is the temporal dimension.

**Comment by LMR2018** [comment]
> 您好，感谢您的关注。
> 你的意思是`np.save()?`
I want to convert the video like this and save it as Npy:

The file should contain an array with shape 15 x 2 x length.
The first dimension (15) corresponds the 15 body joint defined here.
The second dimension (2) corresponds to x and y coordinates.
The third dimension (length) is the temporal dimension.

**Comment by Garfield-kh** [comment]
Hi, is this #10 related to this issue ?

**Comment by LMR2018** [comment]
> 嗨，这个#10与这个问题有关吗？

Ok, thanks. I'll try it. I'd like to convert video to https://github.com/yzhq97/transmomo.pytorch is required in the input skeleton sequences .npy file
