### ISSUE TITLE
about MPJPE of the poseAug

### ISSUE THREAD

**Issue by ZhangLei999** [jfzhang95/PoseAug#25]
Thanks your work! After running the code:
python3 run_poseaug.py --note poseaug --posenet_name 'mlp' --lr_p 1e-4 --stages 2 --checkpoint './checkpoint/poseaug' --keypoints gt
MPJPE of the best model is 41.7. But MPJPE of my pretrained model is 41.3. Is that normal?
I didn't change any code.

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest.
Here is the train [log](https://drive.google.com/file/d/16QMwhWwavd8UOPqc9lKZVfddM-Aa8Bt6/view?usp=sharing) in mlp poseaug setting.
May I ask about your system information: ubuntu, GPU, cuda, pip list?

**Comment by ZhangLei999** [comment]
我训练mlp poseAUG的日志文件, 还有conda.list文件都在这了, 你看看
系统是centos 7.*&nbsp; &nbsp; GPU是2080ti&nbsp; &nbsp; &nbsp;cuda是 11.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jfzhang95/PoseAug"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月10日(星期五) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jfzhang95/PoseAug] about MPJPE of the poseAug (#25)





 
Hi, thank you for the interest.
 Here is the train log in mlp poseaug setting.
 May I ask about your system information: ubuntu, GPU, cuda, pip list?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
