### ISSUE TITLE
How to evaluate the model on 3DPW dataset？

### ISSUE THREAD

**Issue by ZhangRenkai** [jfzhang95/PoseAug#26]
The code only provides how to evaluate on the Human 3.6m dataset and 3DHP dataset, while the PoseAug paper also has a cross-dataset validation on the outdoor 3DPW dataset, but I don't know how to download the dataset and process it as described in the DATASET.md file（DATASET. md file in this project only writes how to process Human 3.6m  and 3DHP dataset）.Hope you can provide the operation method. Thank you very much!

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
Here is the 16 joints gt version [data](https://drive.google.com/file/d/1rgx_SGeGwiLXiRvcOeY4rcriUREEkk2A/view?usp=sharing).
For the preprocessing code, as it belongs to another project, we will release it in the future.
Thank you~
