### ISSUE TITLE
What is the shortest way to get prediction?

### ISSUE THREAD

**Issue by grayskripko** [jfzhang95/PoseAug#29]
I'm not proficient in this type of neural network and, to be honest, don't even understand does it consume video, what format, image, and its format, or what?
I've read carefully README and DATASETS.md files and they have links to other repos as well as require some 3d pose NN knowledge.
I expect this could be helpful to get the shortest way to get one simple prediction for others who aren't deeply involved in this domain. 

If this has value to you, as a data analyst and data scientist, I would expect:
- `python predict.py -input ... -checkpoint ...`
- link to just one "best" checkpoint (there are a number of them now, I don't know what they mean and the difference)
- maybe just a link on an example of one input
- a short description of the output matrix, its columns, and rows.

It's fine if it's not important and you just close the issue. Thank you anyway for the open-sourced solution to the important problem.

**Comment by Garfield-kh** [comment]
Hi, thank you for the insterest!
I think this [post ](https://github.com/facebookresearch/VideoPose3D/issues/2) may meet your need, you can have check.

**Comment by grayskripko** [comment]
thank you very much!
Probably, it could be useful to insert a link to this issue in your README file as a small section.
