### ISSUE TITLE
how to use my own data ( detect 2d keypoints h36m format )

### ISSUE THREAD

**Issue by yeji2021** [jfzhang95/PoseAug#30]
I want to see result with my own video data. So I find some great example to inference video, VideoPose3D. But they use detectron2 to detect keypoints, these keypoints type is COCO. 

So I wonder if you can recommend any open source to detect keypoints, type of H36M, or any idea to change COCO type to H36M?

I tried coco keypoints transform to h36m format, making new h36m keypoints array using copy or calculate from coco.
 ```
new_kp = np.zeros(kp.shape)  # kp is outkeypoints from VideoPose3D/data/prepare_data_2d_custom.py
    new_kp[:, 0, :] = (kp[:, 11, :] + kp[:, 12, :]) / 2  # hip
    new_kp[:, 1, :] = kp[:, 12, :]  # Rhip
    new_kp[:, 2, :] = kp[:, 14, :]  # Rknee
```    
But coco format is insufficient to calculate some keypoints(13 : Thorax, 15 : Head, 12 : Spine).

Thanks for your great works, I have learned a lot from them.

**Comment by woo1** [comment]
I uploaded inference code here
https://github.com/woo1/PoseAug
