### ISSUE TITLE
数据增广区别

### ISSUE THREAD

**Issue by sunmengnan** [jfzhang95/PoseAug#31]
想请问一下，这里用的数据扩增方式和Cascaded Deep Monocular 3D Human Pose Estimation with Evolutionary
Training Data这里提到的方式有什么区别？

**Comment by Garfield-kh** [comment]
Hi, thank you for your interest.
For the difference, do you mean this one?
Evolutionary: random based _Mutation_ + _Crossover_.
Poseaug: learnable _BA, BL, RT_ operation.

**Comment by sunmengnan** [comment]
Yes。。。

**Comment by sunmengnan** [comment]
I think they make no big difference

**Comment by Garfield-kh** [comment]
ummm, the difference between random augmentation and [AutoAugment](https://arxiv.org/pdf/1805.09501.pdf)?
