### ISSUE TITLE
Questions about 3D poses View Perspective Generation

### ISSUE THREAD

**Issue by AndyVerne** [jfzhang95/PoseAug#36]
Hi, thanks for the great job.
In this project, I want to figure out that whether the perspective  of 3D poses  view generated by PoseAug is fixed.  For example, in the 3D plot,  does the skeleton always faces to x axis or z axis? 
If not, could you point out how to control or fix the perspective of 3D poses view generated?
I would really appreciate it.
I'm looking forward to your replies.
Best Regards.

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
The view-point invariant 3D pose or canonical poses, you may refer to this [paper](https://arxiv.org/pdf/2004.03143.pdf).
To fix the perspective of view point, you can try [p_mpjpe](https://github.com/jfzhang95/PoseAug/blob/f3f5c4e916ebf7529b873ec1c14c1ce0bf0f5cb1/utils/loss.py#L161), which contains a function of rigid alignment between two poses.
You can set all your pose data as X, and use a T-pose as Y. By align all the X to Y, you can get a pose data which all are face front.

Hope this helps.
Thank you~

**Comment by AndyVerne** [comment]
Thanks so much for the reply. I've got it.
Sorry for the late comment. ; (
