### ISSUE TITLE
Error to setup the environment.

### ISSUE THREAD

**Issue by 4ku** [jfzhang95/PoseAug#37]
I've created conda environment and then did `pip install -r requirements.txt`. But I've got an error:
```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/build/80754af9/numpy_and_numpy_base_1603487797006/work'
```
It seems I don't have files like `file:///tmp/build/80754af9/numpy_and_numpy_base_1603487797006/work`, which are in the requirements. There are temporary files, which I can not get.

**Comment by Garfield-kh** [comment]
Hi, thank you for the insterest!
Can you try this [one](https://stackoverflow.com/questions/22250483/stop-pip-from-failing-on-single-package-when-installing-with-requirements-txt) to skip error and see if it works?

Hope this helps.

**Comment by 4ku** [comment]
I used conda environment from [PoseFormer](https://github.com/zczcwh/PoseFormer) and it works for me:
- Python 3.8.2
- PyTorch 1.7.1
- CUDA 11.0
