### ISSUE TITLE
How to test my picture through this model?

### ISSUE THREAD

**Issue by FinallyKiKi** [jfzhang95/PoseAug#38]

**Comment by jfzhang95** [comment]
Thanks for your interest!
Here are the steps to predict 3D poses (16 joints) from images:

1. Apply [OpenPose ](https://github.com/CMU-Perceptual-Computing-Lab/openpose) or [AlphaPose ](https://github.com/MVIG-SJTU/AlphaPose) to get the detected 2D poses at first. 
2. Then convert the detected 2D poses to 16 joints definition with a similar procedure as  [prepare_data_3dhp.py](https://github.com/jfzhang95/PoseAug/blob/main/data_extra/prepare_data_3dhp.py).
3. Preprocess the 2D pose with the same normalization as the 2D-3D pose model training.
4. Apply the pre-trained 2D-3D pose lifting model on 2D poses to get the 3D pose results.
5. Visualize the 3D pose results with [visualization code](https://github.com/facebookresearch/VideoPose3D/blob/1afb1ca0f1237776518469876342fc8669d3f6a9/common/visualization.py#L62).

**Comment by Garfield-kh** [comment]
Hi, 16-joints-setting video to 3D pose are avaliable [here](https://github.com/Garfield-kh/PoseTriplet)

**Comment by FinallyKiKi** [comment]
> Hi, 16-joints-setting video to 3D pose are avaliable [here](https://github.com/Garfield-kh/PoseTriplet)

Thank you! I will try it later
