### ISSUE TITLE
Hi，方便直接提供下【输入图像/视频 ->输出可视化3d关键点】的端到端推理脚本么，谢谢~

### ISSUE THREAD

**Issue by THU-lsy** [jfzhang95/PoseAug#39]

**Comment by Garfield-kh** [comment]
Hi, thank you for the insterest!
I think you can check this [post ](https://github.com/facebookresearch/VideoPose3D/issues/2) for in-the-wild prediction code.
I will release code about in-the-wild prediction later, but they are not ready yet.
Thank you~

**Comment by Garfield-kh** [comment]
Hi, 16-joints-setting video to 3D pose are avaliable [here ](https://github.com/Garfield-kh/PoseTriplet)

**Comment by THU-lsy** [comment]
> Hi, 16-joints-setting video to 3D pose are avaliable [here ](https://github.com/Garfield-kh/PoseTriplet)

got it, thanks
