### ISSUE TITLE
Question about motion temporal continuity 

### ISSUE THREAD

**Issue by PGogo** [jfzhang95/PoseAug#41]
Thanks for your excellent work!
I wonder if such random augmentation would lead to discontinuity in the motion of successive frames (e.g. VideoPose3D). Since the data enhancement of each frame is based on Gaussian distribution, if the hand is augmented as raised at the t-th frame while it turns to lower at the t+1-th frame. The motion would be deformed and the algorithm relying on time continuity could fail. Isn't it? (I've noticed that PoseAug also has a great improvement over VideoPose3D, just wonder why?)

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
Here the VideoPose3D we used in PoseAug is single-frame setting.
If you are interested in Video level data augmentation, you may consider our recent work [PoseTriplet(CVPR2022)](https://github.com/Garfield-kh/PoseTriplet).
It is under self-supervied setting, but can be change to semi-supervied or augmenation setting.

**Comment by PGogo** [comment]
> Hi, thank you for the interest! Here the VideoPose3D we used in PoseAug is single-frame setting. If you are interested in Video level data augmentation, you may consider our recent work [PoseTriplet(CVPR2022)](https://github.com/Garfield-kh/PoseTriplet). It is under self-supervied setting, but can be change to semi-supervied or augmenation setting.

Thank you for your prompt reply. Exactly, I'm about to refer to PoseTriplet !
