### ISSUE TITLE
About model inference

### ISSUE THREAD

**Issue by deeprine** [jfzhang95/PoseAug#43]
hi.
Follow the instructions in this link to test your pre-trained model.

https://github.com/Garfield-kh/PoseTriplet/tree/main/estimator_inference

3D Joint detectors title part
Change the ckpt_ep_045.bin file to your pre-trained model and use

" RuntimeError: Error(s) in loading sta" te_dict for TemporalModel:
         Unexpected key(s) in state_dict:

An error occurs.

Is my usage incorrect?

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest.
`Unexpected key(s) in state_dict` means the model and weight file does not match.
Here the [estimator_inference](https://github.com/Garfield-kh/PoseTriplet/tree/main/estimator_inference) and PoseAug share the same joint setting (i.e., 16 joints), but their model file is slightly different.
To use it for single frame evaluation, you need to adapt the model file [models_baseline/videopose/model_VideoPose3D.py](https://github.com/jfzhang95/PoseAug/blob/main/models_baseline/videopose/model_VideoPose3D.py) into `estimator_inference`.

**Comment by zhepherd** [comment]
> Hi, thank you for the interest. `Unexpected key(s) in state_dict` means the model and weight file does not match. Here the [estimator_inference](https://github.com/Garfield-kh/PoseTriplet/tree/main/estimator_inference) and PoseAug share the same joint setting (i.e., 16 joints), but their model file is slightly different. To use it for single frame evaluation, you need to adapt the model file [models_baseline/videopose/model_VideoPose3D.py](https://github.com/jfzhang95/PoseAug/blob/main/models_baseline/videopose/model_VideoPose3D.py) into `estimator_inference`.

how to adapt the model file？？
