### ISSUE TITLE
How to plot the view point in the paper ?

### ISSUE THREAD

**Issue by jiangzeyinzi** [jfzhang95/PoseAug#45]
Hi, thank you for outstanding work! 
    I want to know how to plot the view point in the paper for checking the data.
![20220526161103](https://user-images.githubusercontent.com/29306530/170455673-cb49d6e9-6e6a-42e9-a223-0115a58ed83a.jpg)

**Comment by Garfield-kh** [comment]
Hi, this is the [tool ](https://qutip.org/docs/latest/guide/guide-bloch.html) used to plot the figure.
The viewpoint is caculated by align the sample pose to canonical space (i.e, caculate the rotation [p_mpjpe](https://github.com/jfzhang95/PoseAug/blob/f469ce4a6fb3da0b7e5ba21d796c02f61e3e5caf/utils/loss.py#L153) between sample pose and T-pose).

**Comment by jiangzeyinzi** [comment]
> Hi, this is the [tool ](https://qutip.org/docs/latest/guide/guide-bloch.html) used to plot the figure. The viewpoint is caculated by align the sample pose to canonical space (i.e, caculate the rotation [p_mpjpe](https://github.com/jfzhang95/PoseAug/blob/f469ce4a6fb3da0b7e5ba21d796c02f61e3e5caf/utils/loss.py#L153) between sample pose and T-pose).

Thanks for your reply! I will try it.
