### ISSUE TITLE
H36M CPN and GT number of samples and Nose joint question. 

### ISSUE THREAD

**Issue by damonchang23** [jfzhang95/PoseAug#46]
Hi, 
I really appreciate your great work and I have a question about number of joints (16).
I follow your dataset instruction and get H36M(GT2D, GT3D, CPN2D, HR2D).
The number of GT2D sample is (1559752,16,2), however, CPN2D is (1561382,17,2). 
Am I manually except Nose joint(Index 9)? and how can I match total number of samples? 
Thank you for your reply in advance.

**Comment by xiu-cs** [comment]
The problem is that the 2D and 3D sequence lengths are not aligned.
1. You can get the pre-processed joints file (16 joints) from here [pre-processed joints files](https://drive.google.com/drive/folders/1jVyz9HdT0Jq3-YPZnOQ6GEcOVDRZAifK). 
2. If you want to do the alignment manually, you can change the function [create_2d_data](https://github.com/jfzhang95/PoseAug/blob/main/utils/data_utils.py) as follows.
```python 
def create_2d_data(data_path, dataset):
    keypoints = np.load(data_path, allow_pickle=True)
    keypoints = keypoints['positions_2d'].item()
    folder_list =  ['S1', 'S5', 'S6', 'S7', 'S8', 'S9', 'S11']
    for subject in folder_list:
        assert subject in keypoints, 'Subject {} is missing from the 2D detections dataset'.format(subject)
        for action in dataset[subject].keys():
            assert action in keypoints[subject], 'Action {} of subject {} is missing from the 2D detections dataset'.format(action, subject)

            for cam_idx in range(len(keypoints[subject][action])):
                mocap_length = dataset[subject][action]['positions_3d'][cam_idx].shape[0]
                assert keypoints[subject][action][cam_idx].shape[0] >= mocap_length

                if keypoints[subject][action][cam_idx].shape[0] > mocap_length: # 
                    keypoints[subject][action][cam_idx] = keypoints[subject][action][cam_idx][:mocap_length]

    for subject in keypoints.keys():
        for action in keypoints[subject]:
            for cam_idx, kps in enumerate(keypoints[subject][action]):
                cam = dataset.cameras()[subject][cam_idx]
                kps[..., :2] = normalize_screen_coordinates(kps[..., :2], w=cam['res_w'], h=cam['res_h'])
                keypoints[subject][action][cam_idx] = kps

    return keypoints
```

**Comment by GloryyrolG** [comment]
Hi @xiu-cs , may I ask if you have reproduced the [log](https://drive.google.com/file/d/16QMwhWwavd8UOPqc9lKZVfddM-Aa8Bt6/view?usp=sharing) successfully with the current repo? Thanks.
