### ISSUE TITLE
How to inference

### ISSUE THREAD

**Issue by zhepherd** [jfzhang95/PoseAug#47]
How to inference？？ the inference code  you provide is PoseTriplet， i don‘t know how use to our model

**Comment by jfzhang95** [comment]
Hi, please refer to issue https://github.com/jfzhang95/PoseAug/issues/43.

**Comment by zhepherd** [comment]
how to adapt the model file？？

**Comment by Garfield-kh** [comment]
you need to replace the model network file and rename key when save or load model so that they are match.
