### ISSUE TITLE
How to make npy file?

### ISSUE THREAD

**Issue by redorangeyellowy** [jfzhang95/PoseAug#48]
Thank you for your excellent research.

`https://github.com/jfzhang95/PoseAug/blob/main/data_extra/bone_length_npy/hm36s15678_bl_templates.npy`

I wonder how this file was created.

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest.
This is created by caculate the length between adjacent joint (eg, from LElbow to LWrist is the length of LElbow).

**Comment by redorangeyellowy** [comment]
Thank you for your reply.

**Comment by luckcodingdog** [comment]
@Garfield-kh I have the same question about the './data_extra/bone_length_npy/hm36s15678_bl_templates.npy'.
The shape of ndarry is [5,15]. what's the meaning of it? why the row is 5?
Another question, i want to apply PoseAug on coco-wholebody dataset (133 keypoints). 
Do you have some suggestions about this?
Thanks in advance and look forward for your suggestion.
