### ISSUE TITLE
trajectory model training

### ISSUE THREAD

**Issue by darcula1993** [jfzhang95/PoseAug#49]
I am trying to use this training frame to train a baseline trajectory model (predict root node camera space position). It works but loss seems weird: the test MPJPE is always around 110. 

Is there anything I miss? Have you tried train any trajectory model for PoseAug model?

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest.
No, I didn't try trajectory model in single frame setting.
The [VideoPose3D](https://github.com/facebookresearch/VideoPose3D) provide trajectory model for multi-frame setting, and I used it in [PoseTriplet](https://github.com/Garfield-kh/PoseTriplet).

**Comment by darcula1993** [comment]
Thank you for your reply.
The single frame traj model from VideoPose3D (test MPJPE around 110) for Poseaug works pretty well! It just weird that test mpjpe is such high.
