### ISSUE TITLE
About extra 2D pose datasets (MPII&LSP) data pre-processing and training problem 

### ISSUE THREAD

**Issue by wenwen12321** [jfzhang95/PoseAug#50]
Hi author. Thanks for the great work!

I'm still not clear on data pre-processing.
Could you please release the code or point me how to use additional in-the-wild 2D poses (MPII & LSP) to train the 2D discriminator? Which you mention in paper page 6 "Results on 3DHP (cross-scenario) part".

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
Since the 2D dataset are COCO format, you will need to convert it to 16 joints setting.
Here are the issue related to the conversion #4 #12 .
Meanwhile, we remove some of the 2D data which are too far/small or too close/big to the camera.

**Comment by wenwen12321** [comment]
I've got it! Thanks for the very informative response!
