### ISSUE TITLE
hrnet 2d 数据

### ISSUE THREAD

**Issue by qiqiApink** [jfzhang95/PoseAug#51]
请问，您可以提供一下 hrnet 在 hm36 上的 17 个关键点的数据吗，就是相比于您 16 个关键点文件删减之前的，或者是您可以告知一下哪里可以下载吗？

**Comment by Garfield-kh** [comment]
Hi~ 这个: https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/TRAINING.md

**Comment by qiqiApink** [comment]
非常感谢！
