### ISSUE TITLE
questions  about train

### ISSUE THREAD

**Issue by mirror0129** [jfzhang95/PoseAug#53]
Hi, I'm new in this field, so the questions might be stupid. I have my own data set and I saw the DATASET file, but I still have some questions. First, my own data set is made of many npy_file, and the node number is different from the Human3.6D, should I change the node number of train model, and how could I do this. Second, I want to use my data set, how could I do?
Sry for my silly questions again, but I cant get suit solutions to handle them😭

**Comment by Garfield-kh** [comment]
Hi, if you want to train your data with Human 3.6, you have to make them the same format, says all joint follow the same order and definition. 
For change the order in npy_file, it's basic python numpy skill.
