### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by davidpengiupui** [jfzhang95/PoseAug#54]
Thanks so much for your wonderful work and help! I used the code in PoseTriplet to do inference. It works very well with the model provided by PoseTriplet. However, when I tried to use the model trained here to test, it doesn't work as their weights are not matching. The problem lies in Line 36 of function_baseline/model_pos_preparation.py, where the output joint number is 15, while that in PoseTriplet is 16. Could you please tell me how to solve it?

**Comment by Garfield-kh** [comment]
Hi thank you for your interest.
The output numbder 15 means it assume the root is 0. 
To solve it, you need to change the model file in the visualization to follow the same setting as it's training framework.

Hope this helps.

**Comment by davidpengiupui** [comment]
Thank you for your explanation!
