### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by lyumingzhi** [jfzhang95/PoseAug#7]
Hi thank you for your great work! May i ask whether and when you can share your pretrained model?

**Comment by Garfield-kh** [comment]
Hi,
Thanks for your interest!
Here are the pretrained baseline models under GT setting and the one (STGCN-GT) trained with PoseAug: [./checkpoint](https://drive.google.com/drive/folders/1mLttbyZxsRdN5kw1IRdzZozyfndhV3Wh?usp=sharing)
You can download them and place at `./checkpoint`.
Evaluate the PoseAug one by `python3 run_evaluate.py --posenet_name 'stgcn' --keypoints gt --evaluate ./checkpoint/poseaug/stgcn/gt/poseaug/ckpt_best_dhp_p1.pth.tar`.

**Comment by agarwalsau** [comment]
@Garfield-kh The pre-trained weight link seems to be broken.

**Comment by saurav4098** [comment]
@Garfield-kh I am not able to download the pre-trained model with the link provided. Can you please help me with this
