### ISSUE TITLE
code for evaluation

### ISSUE THREAD

**Issue by gravitychen** [jfzhang95/PoseAug#9]
great work! 

can you share the preprocess code for 3DPW?

thank you very much

**Comment by Garfield-kh** [comment]
Thanks for your interest!
We adopt the preprocess code for 3DPW from [SPIN](https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/pw3d.py).
And then convert the preprocessed data to 16 joints definitions with a similar procedure as  [prepare_data_3dhp.py](https://github.com/jfzhang95/PoseAug/blob/main/data_extra/prepare_data_3dhp.py).

Hope this helps.

**Comment by gravitychen** [comment]
Thank you very much for your great work!
